workspace 'backendless'

xcodeproj 'backendlessAPI/backendlessAPI.xcodeproj'

target 'backendless-device' do
    use_frameworks!
    workspace 'backendless'
    pod 'Socket.IO-Client-Swift'
end

target 'backendless-mac' do
end

target 'backendless-simulator' do
    use_frameworks!
    workspace 'backendless'
    pod 'Socket.IO-Client-Swift'
end

target 'bkndlss-device' do
    use_frameworks!
    workspace 'backendless'
    pod 'Socket.IO-Client-Swift'
end

target 'bkndlss-simulator' do
    use_frameworks!
    workspace 'backendless'
    pod 'Socket.IO-Client-Swift'
end
